### ISSUE TITLE
Specifications menu bar returns 404

### ISSUE THREAD

**Issue by awatson1978** [Open-Health-Manager/patient-data-receipt-ig#7]

**Comment by awatson1978** [comment]
Hmmm.  Online version at https://open-health-manager.github.io/patient-data-receipt-ig/index.html doesn't reflect content at docs/index.html.

**Comment by awatson1978** [comment]
@karlnaden Do you have any visibility into the deploy scripts?  I bumped the version to v0.2.2, which is now reflected online.  But the menu bar isn't the same between local and deployed build.  Are the deploy scripts adjusting any files?

**Comment by karlnaden** [comment]
I do not. I think the deploy scripts I had set up originally deployed to a separate repo. I thoughts that @awatson1978 you were the one that updated to a single-repo model. However, I don't see that other repo anymore, so maybe my memory isn't accurate.

**Comment by nkarip** [comment]
The github workflow is building the IG and pushing to gh-pages, so /docs is not longer referenced. Please do not commit the build to the repo.
